name: login_page_flutter_demo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  auto_route: ^9.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.15
  easy_localization: ^3.0.7

dev_dependencies:
  auto_route_generator: ^9.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.13
  
flutter: 
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/icons/
    - assets/translations/
